name: Docker

on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile, Dockerfile, Dockerfile]  # Specify 'Dockerfile' for each subdirectory

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          directory=$(dirname "${{ matrix.dockerfile }}")
          dockerfile="${{ matrix.dockerfile }}"
          image_name="carma-messenger"  # Set your desired image name here
          echo "Building $image_name from $dockerfile in $directory"
          docker build -t $image_name -f "$GITHUB_WORKSPACE/$directory/$dockerfile" "$GITHUB_WORKSPACE/$directory"
          docker tag $image_name "${image_name}:$(basename $directory)"
