name: Docker

on:
  push:
    branches-ignore:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push carma-messenger-ui Docker Image
        run: |
          docker build -t usdotfhwastoldev/carma-messenger-ui:${{ github.ref_name }}-carma-messenger-ui -f Dockerfile .
          docker push usdotfhwastoldev/carma-messenger-ui:${{ github.ref_name }}-carma-messenger-ui
        working-directory: ./carma-messenger-ui/

      - name: Build and Push chevrolet_tahoe_2018 Docker Image
        run: |
          docker build -t usdotfhwastoldev/carma-messenger-config:${{ github.ref_name }}-chevrolet_tahoe_2018 -f Dockerfile .
          docker push usdotfhwastoldev/carma-messenger-config:${{ github.ref_name }}-chevrolet_tahoe_2018  
        working-directory: ./carma-messenger-config/chevrolet_tahoe_2018/

      - name: Build and Push development Docker Image
        run: |
          docker build -t usdotfhwastoldev/carma-messenger-config:${{ github.ref_name }}-development -f Dockerfile .
          docker push usdotfhwastoldev/carma-messenger-config:${{ github.ref_name }}-development
        working-directory: ./carma-messenger-config/development/

      - name: Build and Push carma-messenger-core Docker Image
        run: |
          docker build -t usdotfhwastoldev/carma-messenger-core:${{ github.ref_name }}-carma-messenger-core -f Dockerfile .
          docker push usdotfhwastoldev/carma-messenger-core:${{ github.ref_name }}-carma-messenger-core
        working-directory: ./carma-messenger-core/
      

