name: Docker

on:
  push:

jobs:
  chevrolet_tahoe_2018:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: GITHUB_WORKSPACE/carma-messenger-config/chevrolet_tahoe_2018/Dockerfile
      - run: ls -la && pwd    
  development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: GITHUB_WORKSPACE/carma-messenger-config/development/Dockerfile
  carma-messenger-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: GITHUB_WORKSPACE/carma-messenger-ui/Dockerfile                 
  carma-messenger-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: GITHUB_WORKSPACE/carma-messenger-core/Dockerfile         